### ISSUE TITLE
Mongo with Replica Set

### ISSUE THREAD

**Issue by FabianElsmer** [GreyRook/dockerdb#7]
The mongo fixture does not support using replica sets for the test. Sadly for some features of mongodb to work (like changeStreams) the mongod service needs to be started with a replica set, even if there is no second container.

* dockerdb version: 0.2.0
* Python version: 3.6.8
* Operating System: Fedora 29

**Comment by FabianElsmer** [comment]
The newest dockerdb version (0.4.0) actually supports this, but throws an error during initialization:
self.port should be self.exposed_port


    def check_ready(self):
        """Check if something responds to ``url``."""
        import pymongo.errors
    
        client = self.pymongo_client()
        try:
            is_master = client.admin.command('ismaster')
        except pymongo.errors.ConnectionFailure:
            return False
    
        if self.replicaset and not self.replicaset_ready:
>           host = '{}:{}'.format(self.ip_address(), self.port)
E           AttributeError: 'Mongo' object has no attribute 'port'

**Comment by FabianElsmer** [comment]
Please merge
https://github.com/GreyRook/dockerdb/pull/8

**Comment by FlorianLudwig** [comment]
Done
